### ISSUE TITLE
Chapitre neveRending identifiants introuvables 

### ISSUE THREAD

**Issue by LKOOE0** [InseeFrLab/funcamp-r-icarius#1]
Impossible de savoir quels identifiants rentrer sur Rstudio via sspcloud pour accéder au dernier chapitre
![Rstudio](https://user-images.githubusercontent.com/75686010/101749959-a9b7c880-3ace-11eb-98cd-92411efdc288.png)
Kevin CHAPUT

**Comment by LKOOE0** [comment]
J'ai trouvé la réponse:
username=icarius
pasword= statia
Serait-il possible de rajouter cette information dans le i du service sspcloud avec le enjoy ;-) ?

**Comment by insee-unissi** [comment]
Merci pour avoir signalé l'anomalie. Le tutoriel qui introduit le lancement de la partie neverending a été actualisé en conséquence pour préciser le username et le password.
